-- ==========================================
-- MASTER DATABASE SETUP FOR HOTEL SYSTEM
-- ==========================================

-- 1. ตารางห้องพัก
CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_number TEXT UNIQUE NOT NULL,
  room_type TEXT NOT NULL,
  price_per_night NUMERIC NOT NULL,
  status TEXT DEFAULT 'available',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ตารางการจอง
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id),
  guest_name TEXT NOT NULL,
  check_in TIMESTAMPTZ NOT NULL,
  check_out TIMESTAMPTZ NOT NULL,
  total_price NUMERIC,
  status TEXT DEFAULT 'confirmed',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ตารางบัญชีรายรับ-รายจ่าย
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount NUMERIC NOT NULL,
  type TEXT NOT NULL, -- 'income' หรือ 'expense'
  description TEXT,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ข้อมูลเริ่มต้น (ห้องพัก 51 ห้อง)
INSERT INTO rooms (room_number, room_type, price_per_night) VALUES
('A101', 'Standard', 400), ('A102', 'Standard', 400), ('A103', 'Standard', 400),
('A104', 'Standard', 400), ('A105', 'Standard', 400), ('A106', 'Standard Twin', 500),
('A107', 'Standard Twin', 500), ('A108', 'Standard Twin', 500), ('A109', 'Standard Twin', 500),
('A110', 'Standard Twin', 500), ('A111', 'Standard', 400), ('A201', 'Standard', 400),
('A202', 'Standard', 400), ('A203', 'Standard', 400), ('A204', 'Standard', 400),
('A205', 'Standard', 400), ('A206', 'Standard', 400), ('A207', 'Standard', 400),
('A208', 'Standard', 400), ('A209', 'Standard', 400), ('A210', 'Standard', 400),
('A211', 'Standard', 400), ('B101', 'Standard', 400), ('B102', 'Standard', 400),
('B103', 'Standard', 400), ('B104', 'Standard', 400), ('B105', 'Standard', 400),
('B106', 'Standard', 400), ('B107', 'Standard', 400), ('B108', 'Standard', 400),
('B109', 'Standard', 400), ('B110', 'Standard', 400), ('B111', 'Standard Twin', 500),
('B201', 'Standard', 400), ('B202', 'Standard', 400), ('B203', 'Standard', 400),
('B204', 'Standard', 400), ('B205', 'Standard', 400), ('B206', 'Standard', 400),
('B207', 'Standard', 400), ('B208', 'Standard', 400), ('B209', 'Standard', 400),
('B210', 'Standard', 400), ('B211', 'Standard', 400), ('N1', 'Standard Twin', 600),
('N2', 'Standard', 500), ('N3', 'Standard', 500), ('N4', 'Standard Twin', 600),
('N5', 'Standard Twin', 600), ('N6', 'Standard Twin', 600), ('N7', 'Standard', 500)
ON CONFLICT (room_number) DO NOTHING;
