-- =========================================================
-- COMPLETE HOTEL & RENTAL MANAGEMENT MASTER SCHEMA
-- =========================================================

-- 1. ตารางห้องพัก (Rooms)
CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number TEXT UNIQUE NOT NULL,
    room_type TEXT,
    price_per_night NUMERIC,
    rental_type TEXT DEFAULT 'daily',
    status TEXT DEFAULT 'available',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ตารางข้อมูลลูกค้า (Customers) - จากหน้า '2-1 ลูกค้า'
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    id_card TEXT UNIQUE,
    phone TEXT,
    birth_date TEXT,
    address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ตารางการจองห้อง (Reservations) - จากหน้า '2-2 จองห้อง'
CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number TEXT REFERENCES rooms(room_number),
    customer_name TEXT,
    check_in DATE,
    check_out DATE,
    status TEXT DEFAULT 'confirmed', -- 'pending', 'confirmed', 'cancelled'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ตารางบัญชี (Accounting) - จากหน้า 'สมุดบัญชี'
CREATE TABLE IF NOT EXISTS accounting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT,
    item_name TEXT NOT NULL,
    income NUMERIC DEFAULT 0,
    expense NUMERIC DEFAULT 0,
    total_balance NUMERIC,
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ตารางมิเตอร์น้ำไฟ (Utilities) - จากหน้า 'ประวัติมิเตอร์น้ำไฟ'
CREATE TABLE IF NOT EXISTS utilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number TEXT REFERENCES rooms(room_number),
    month_name TEXT,
    electricity_meter NUMERIC,
    water_meter NUMERIC,
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);
